name: Build and Distribute Executables on Windows

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build server
      run: cl server.cpp /Fe: mypi.exe /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um" /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared"

    - name: Build client
      run: cl client.cpp /Fe: wheremypi.exe /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um" /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-executables
        path: |
          mypi.exe
          wheremypi.exe
